### ISSUE TITLE
关于Linux/macOS支持

### ISSUE THREAD

**Issue by kciok** [xiaohuohumax/auto-unpack#1]
其实直接用p7zip包就行了。运行的时候把.../auto-unpack/util7zip/util7z.py中的lib7zip_path变量值改成str:'7z'即可。

但是要求环境安装p7zip包。

**Comment by xiaohuohumax** [comment]
请移步 [PR 3](https://github.com/xiaohuohumax/auto-unpack/pull/3#issuecomment-2216635516)
