### ISSUE TITLE
能否定制

### ISSUE THREAD

**Issue by xiaocaitu** [xiaohuohumax/auto-unpack#4]
大佬好，我希望时解压缩，然后，在解压后的文件夹中添加几个文件，然后再压缩下

**Comment by xiaohuohumax** [comment]
**抱歉哦~暂不支持定制 😅，不过这里可以提供思路💡（两种解决方式）**

首先初始项目 `auto-unpack init project-name` 然后模板选择 `自定义插件模板`，接着编写自定义插件，请参考：[自定义插件编写](https://xiaohuohumax.github.io/auto-unpack/plugins/custom/)

**第一种：不解压文件，直接给压缩包添加额外文件（优：处理高效，缺：编写复杂）。**

大致实现：利用 7-zip 的添加文件命令（7z a archive.zip ./add-file/*） ，编写新插件（new-archive）继承内置插件 [archive](https://xiaohuohumax.github.io/auto-unpack/plugins/builtin/archive/) 添加（add）子命令，参考：[archive 源码](https://github.com/xiaohuohumax/auto-unpack/blob/main/auto_unpack/plugins/archive.py#L660-L670)，[7-zip 命令文档](https://github.com/xiaohuohumax/auto-unpack/blob/main/auto_unpack/util/sevenzip/lib/7-zip.chm)。

执行流程：

1. 扫描压缩包（scan）
2. 为压缩包添加文件（new-archive）

**第二种：按照你描述的流程，先解压，接着添加文件，再压缩（优：编写简单，缺：中间文件较多）。**

解压功能已经支持，但你需要编写两个插件：拷贝文件到解压文件夹插件（例如：join-files），压缩文件夹插件（例如：zip）。

> [!tip]
> 插件 `上下文` 简单解释：就是扫描到的文件或文件夹

拷贝文件到解压文件夹插件：将需要添加的文件拷贝到 `上下文` 中的文件夹中
压缩文件夹插件：随便找一个压缩文件的库（python 比如内置库 zipfile），将 `上下文` 中的文件夹压缩到指定目录

执行流程：

1. 扫描压缩包（scan）
2. 解压压缩包（archive）
3. 扫描解压文件夹（scan）
4. 拷贝文件到解压文件夹（join-files）
5. 压缩文件夹（zip）
6. 扫描中间文件（scan）：解压文件夹，原压缩包等
7. 清理中间文件（remove）

**以上就是大致思路：但终归还是没测试，只是思路，需要你自行实践 🤭🤭🤭🤭**
